# Generated by Django 3.1.2 on 2020-10-14 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('task', models.CharField(max_length=50, verbose_name='task')),
                ('done', models.BooleanField(default=False, verbose_name='done')),
            ],
        ),
    ]
